### ISSUE TITLE
Version of UUID generated

### ISSUE THREAD

**Issue by avinmathew** [assaf/uuid#33]
Which UUID version is used by this gem to generate UUIDs?

From my understanding of [Variants and versions of UUIDs on Wikipedia](http://en.wikipedia.org/wiki/Universally_unique_identifier#Variants_and_versions), the character `M` defines the version and should be either set to `1`, `2`, `3`, `4`, or `5`. However, when I generate a UUID using this gem, the `M` character appears to be always set to `0`. I would have expected it to be set to `1` since the gem README indicates that the MAC address is used as part of generation.

**Comment by hamiltop** [comment]
Why did this get closed? The UUIDs are not generated according the the RFC cited.

PR at https://github.com/assaf/uuid/pull/53 to correctly set them.
