### ISSUE TITLE
You checked in the bundler binstub of bin/uuid

### ISSUE THREAD

**Issue by postmodern** [assaf/uuid#35]
`bin/uuid` is bundler binstub and cannot be executed.

<pre>
$ uuid
/home/hal/.gem/ruby/1.9.3/gems/bundler-1.3.5/lib/bundler/rubygems_integration.rb:280:in `block in replace_bin_path': can't find executable uuid (Gem::Exception)
	from /home/hal/.gem/ruby/1.9.3/gems/uuid-2.3.7/bin/uuid:16:in `<top (required)>'
	from /home/hal/.gem/ruby/1.9.3/bin/uuid:19:in `load'
	from /home/hal/.gem/ruby/1.9.3/bin/uuid:19:in `<main>'
</pre>

**Comment by kentliau** [comment]
#42
