### ISSUE TITLE
Errno::EACCES: Permission denied - /root/.ruby-uuid

### ISSUE THREAD

**Issue by alexey** [assaf/uuid#38]
When trying to:

``` ruby
self.edit_token = UUID.generate(:compact)
```

trace:

``` ruby
/gems/uuid-2.3.7/lib/uuid.rb:270 in "initialize"
/gems/uuid-2.3.7/lib/uuid.rb:270 in "open"
/gems/uuid-2.3.7/lib/uuid.rb:270 in "initialize"
/gems/uuid-2.3.7/lib/uuid.rb:127 in "new"
/gems/uuid-2.3.7/lib/uuid.rb:127 in "generate"
/app/models/product.rb:46 in "block in <class:Product>"
```

application is ran by root user with unicorn+nginx, deployed with capistrano.
from rails console its working normally on same server

**Comment by agrass** [comment]
I have the same error, anybody knows why is looking for something in root folder?

**Comment by agrass** [comment]
problem solved, I realize that the issue was due the /tmp/ruby-uuid was without permissions for that user
