### ISSUE TITLE
Add License information to Gemspec

### ISSUE THREAD

**Issue by coreyhaines** [assaf/uuid#40]
This will make it show up on rubygems.org. I'm doing due diligence on our gems and need to find out the licenses for all the gems. Having it show up on rubygems.org cuts out the step of having to go to the github repo.

**Comment by jdickey** [comment]
Two and a half years after @coreyhaines, I'm doing due diligence on *our* Gems and find that `uuid` is listed in our `Gemfile.lock` as being dependent on [`macaddr`](https://rubygems.org/gems/macaddr) and [`systemu`](https://rubygems.org/gems/systemu), both of which are licensed under the [Ruby License](https://www.ruby-lang.org/en/about/license.txt). We're uncertain/uneasy about copyleft restrictions introduced by this Gem and would appreciate clarification.

/ping @mitpaladin

**Comment by radar** [comment]
This was done in e04643e178a5b985036d2beba6478fc912dc3f9e.
