### ISSUE TITLE
"Gemfile not found" when using rbenv

### ISSUE THREAD

**Issue by thomaswitt** [assaf/uuid#42]
I installed uuid using rbenv. When calling the command line tool, I get:

/Users/mac/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/uuid-2.3.7/Gemfile not found

**Comment by kentliau** [comment]
#35

**Comment by jdickey** [comment]
Can we get a Gem release that includes current `master`, particularly Commit 532722f? This looks like it would help #42 and #35.

**Comment by radar** [comment]
@jdickey A bit delayed, but uuid v2.3.9 now contains this fix.
