### ISSUE TITLE
Unique and random uuid

### ISSUE THREAD

**Issue by SydOps** [assaf/uuid#48]
When generate uuid, the result are very similar, not random, I understand they are unique. But is it possible to generate a new uuid that different in each range(split by `-`) each time?

```
irb(main):004:0> uuid.generate
=> "1c534e40-ebf3-0132-224b-20c9d088be77"
irb(main):005:0> uuid.generate
=> "1ce35a30-ebf3-0132-224b-20c9d088be77"
```

**Comment by knovoselic** [comment]
Yeah, you can use `SecureRandom.uuid` for that:

    [1] pry(main)> SecureRandom.uuid
    "f9f5fd91-7d05-489a-af56-c813740dcb32"
    [2] pry(main)> SecureRandom.uuid
    "849e8d4b-4f54-4611-818a-c5174930f245"

**Comment by SydOps** [comment]
@knovoselic 

Is the function in this repository?

**Comment by knovoselic** [comment]
It's part of Ruby Standard Library. Check it out here:
http://ruby-doc.org/stdlib-2.2.3/libdoc/securerandom/rdoc/index.html

**Comment by SydOps** [comment]
@knovoselic 

Quota from:http://stackoverflow.com/questions/16650764/securerandom-uuid-vs-uuid-gem

```
From the docs I gather that the gem is more "safe" to be a real unique UUID while SecureRandom.uuid is more of a random string which has a larger chance of not being unique. In addition UUID seems to allow a file-based persistence to assist with this.
```

**Comment by knovoselic** [comment]
I really don't think that's something to be worried about. Also, `SecureRandom` uses `/dev/urandom` which is more secure than just using a random number generator which is seeded by time.
Finally, if you want to generate UUIDs which are considerably different, AFAIK you have no other option than to use a lib that support UUID v4.
