### ISSUE TITLE
Version 2.3.7 or 2.3.8

### ISSUE THREAD

**Issue by arturoherrero** [assaf/uuid#49]
There is a [version 2.3.8][1] in Rubygems but I cannot see the changes in the source code. Where is the code of this version?

[1]: https://rubygems.org/gems/uuid/versions/2.3.8

**Comment by arturoherrero** [comment]
@assaf can you give me some feedback about that, please?

**Comment by assaf** [comment]
I'm pretty sure that would be master at the time it was released.

**Comment by arturoherrero** [comment]
Master is 2.3.7
https://github.com/assaf/uuid/blob/master/uuid.gemspec#L3

**Comment by assaf** [comment]
If you look at the files in the gems and compare them to master, that would answer your question.

**Comment by arturoherrero** [comment]
Yes, but I think that we should reconcile the source code on GitHub with the gem code to prevent confusions. Anyway, thanks!
