### ISSUE TITLE
How does this compare to SecureRandom.uuid?

### ISSUE THREAD

**Issue by janko-m** [assaf/uuid#50]
The Ruby standard library already has a UUID generator, `SecureRandom.uuid`. I thought it would be good to mention in the README how does this gem compare to `SecureRandom.uuid`, and what are the advantages of using this gem.

**Comment by karloku** [comment]
SecureRandom.uuid generates a UUID Version 4. This gem is meant to generate a UUID Version 1.

v4 is more secure, but has a chance to get conflict (though the chance is extremely small).
v1 is guessable because of its generation rule.

**Comment by assaf** [comment]
V1 includes the server's MAC address and time stamp. That makes it easy to trace UUIDs to their source, and possible to sort them in chronological order, which can be useful for troubleshooting; but it's also handed to tell them apart.

V1 is the opposite of secure: it's very easy to guess the next UUID.
